# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/noble.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/noble.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/noble.proto\x12\x05nobel\"N\n\x14\x43\x61tegoryRangeRequest\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\x12\x12\n\nstart_year\x18\x02 \x01(\x05\x12\x10\n\x08\x65nd_year\x18\x03 \x01(\x05\"!\n\x0eKeywordRequest\x12\x0f\n\x07keyword\x18\x01 \x01(\t\"2\n\x0bNameRequest\x12\x11\n\tfirstname\x18\x01 \x01(\t\x12\x10\n\x08lastname\x18\x02 \x01(\t\"\x1b\n\nCountReply\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\"9\n\rLaureateReply\x12(\n\tlaureates\x18\x01 \x03(\x0b\x32\x15.nobel.LaureateRecord\"i\n\x0eLaureateRecord\x12\x11\n\tfirstname\x18\x01 \x01(\t\x12\x10\n\x08lastname\x18\x02 \x01(\t\x12\x0c\n\x04year\x18\x03 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x04 \x01(\t\x12\x12\n\nmotivation\x18\x05 \x01(\t2\xf2\x01\n\x0cNobelService\x12Q\n\x1fGetLaureateCountByCategoryRange\x12\x1b.nobel.CategoryRangeRequest\x1a\x11.nobel.CountReply\x12O\n#GetLaureateCountByMotivationKeyword\x12\x15.nobel.KeywordRequest\x1a\x11.nobel.CountReply\x12>\n\x12\x46indLaureateByName\x12\x12.nobel.NameRequest\x1a\x14.nobel.LaureateReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.noble_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CATEGORYRANGEREQUEST']._serialized_start=28
  _globals['_CATEGORYRANGEREQUEST']._serialized_end=106
  _globals['_KEYWORDREQUEST']._serialized_start=108
  _globals['_KEYWORDREQUEST']._serialized_end=141
  _globals['_NAMEREQUEST']._serialized_start=143
  _globals['_NAMEREQUEST']._serialized_end=193
  _globals['_COUNTREPLY']._serialized_start=195
  _globals['_COUNTREPLY']._serialized_end=222
  _globals['_LAUREATEREPLY']._serialized_start=224
  _globals['_LAUREATEREPLY']._serialized_end=281
  _globals['_LAUREATERECORD']._serialized_start=283
  _globals['_LAUREATERECORD']._serialized_end=388
  _globals['_NOBELSERVICE']._serialized_start=391
  _globals['_NOBELSERVICE']._serialized_end=633
# @@protoc_insertion_point(module_scope)
