# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import noble_pb2 as proto_dot_noble__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/noble_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NobelServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLaureateCountByCategoryRange = channel.unary_unary(
                '/nobel.NobelService/GetLaureateCountByCategoryRange',
                request_serializer=proto_dot_noble__pb2.CategoryRangeRequest.SerializeToString,
                response_deserializer=proto_dot_noble__pb2.CountReply.FromString,
                _registered_method=True)
        self.GetLaureateCountByMotivationKeyword = channel.unary_unary(
                '/nobel.NobelService/GetLaureateCountByMotivationKeyword',
                request_serializer=proto_dot_noble__pb2.KeywordRequest.SerializeToString,
                response_deserializer=proto_dot_noble__pb2.CountReply.FromString,
                _registered_method=True)
        self.FindLaureateByName = channel.unary_unary(
                '/nobel.NobelService/FindLaureateByName',
                request_serializer=proto_dot_noble__pb2.NameRequest.SerializeToString,
                response_deserializer=proto_dot_noble__pb2.LaureateReply.FromString,
                _registered_method=True)


class NobelServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetLaureateCountByCategoryRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLaureateCountByMotivationKeyword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindLaureateByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NobelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLaureateCountByCategoryRange': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLaureateCountByCategoryRange,
                    request_deserializer=proto_dot_noble__pb2.CategoryRangeRequest.FromString,
                    response_serializer=proto_dot_noble__pb2.CountReply.SerializeToString,
            ),
            'GetLaureateCountByMotivationKeyword': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLaureateCountByMotivationKeyword,
                    request_deserializer=proto_dot_noble__pb2.KeywordRequest.FromString,
                    response_serializer=proto_dot_noble__pb2.CountReply.SerializeToString,
            ),
            'FindLaureateByName': grpc.unary_unary_rpc_method_handler(
                    servicer.FindLaureateByName,
                    request_deserializer=proto_dot_noble__pb2.NameRequest.FromString,
                    response_serializer=proto_dot_noble__pb2.LaureateReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nobel.NobelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nobel.NobelService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NobelService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetLaureateCountByCategoryRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nobel.NobelService/GetLaureateCountByCategoryRange',
            proto_dot_noble__pb2.CategoryRangeRequest.SerializeToString,
            proto_dot_noble__pb2.CountReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLaureateCountByMotivationKeyword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nobel.NobelService/GetLaureateCountByMotivationKeyword',
            proto_dot_noble__pb2.KeywordRequest.SerializeToString,
            proto_dot_noble__pb2.CountReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindLaureateByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nobel.NobelService/FindLaureateByName',
            proto_dot_noble__pb2.NameRequest.SerializeToString,
            proto_dot_noble__pb2.LaureateReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
